name: pip_services3_grpc
version: 1.1.1
description: This component library is a part of the [Pip.Services](https://github.com/pip-services/pip-services) project.It provides the following synchronous communication components.
homepage: https://github.com/pip-services3-dart/pip-services3-grpc-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pip_services3_commons: ^1.1.3
  pip_services3_components: ^1.1.2
  pip_services3_rpc: ^1.1.1
  grpc: ^3.0.2
  protobuf: ^2.0.0
  fixnum: ^1.0.0

dev_dependencies:
  test: ^1.17.12