name: pip_services3_grpc
version: 1.0.0
author: Sergey Seroukhov <seroukhov@gmail.com>
description: This component library is a part of the [Pip.Services](https://github.com/pip-services/pip-services) project.It provides the following synchronous communication components.
homepage: https://github.com/pip-services3-dart/pip-services3-grpc-dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  pip_services3_commons: ">=1.0.2 <2.0.0"
  pip_services3_components: ">=1.0.4 <2.0.0"
  pip_services3_rpc: ">=1.0.1 < 2.0.0"
  grpc: ^2.1.3
  protobuf: ^1.0.1
  fixnum: ^0.10.11

dev_dependencies:
  test: '>=1.14.2 <2.0.0'